// frontend/src/components/PostDetail.vue
<template>
  <section v-if="loading" class="card">
    <p>{{ t('postDetail.loading') }}</p>
  </section>
  <section v-else-if="error || !postDetail" class="card">
    <p style="color: #dc2626">{{ error || t('postDetail.notFound') }}</p>
    <button v-if="onBack" class="btn" @click="onBack">
      {{ t('postDetail.back') }}
    </button>
  </section>
  <section v-else class="card">
    <div v-if="onBack" style="margin-bottom: 1rem">
      <button class="btn" @click="onBack" style="margin-bottom: 1rem">
        ← {{ t('postDetail.back') }}
      </button>
    </div>

    <!-- Post Header -->
    <div class="post-header" style="margin-bottom: 1rem; padding-bottom: 1rem; border-bottom: 1px solid #e5e7eb">
      <div class="post-author" style="display: flex; align-items: center; gap: 1rem">
        <div 
          class="post-avatar" 
          style="cursor: pointer"
          @click="handleViewAuthorProfile"
        ></div>
        <div style="flex: 1">
          <div style="display: flex; align-items: center; gap: 0.5rem">
            <div 
              class="post-author-name"
              style="cursor: pointer"
              @click="handleViewAuthorProfile"
            >{{ postDetail.authorDisplayName || postDetail.authorName || t('postList.anonymous') }}</div>
            <span class="post-author-badge">{{ t('postList.student') }}</span>
          </div>
          <div 
            style="font-size: 0.875rem; color: #666; margin-top: 0.25rem; cursor: pointer"
            @click="handleViewAuthorProfile"
          >
            @{{ postDetail.authorName }}
          </div>
        </div>
        <button
          v-if="currentUserId && postDetail.authorId && currentUserId !== postDetail.authorId"
          :class="['btn', postDetail.isFollowing ? '' : 'btn-primary']"
          @click="handleToggleFollow"
          style="padding: 0.5rem 1rem; font-size: 0.875rem"
        >
          {{ postDetail.isFollowing ? t('postDetail.following') : t('postDetail.follow') }}
        </button>
      </div>
    </div>

    <!-- Post Content -->
    <h1 class="post-title" style="
      font-size: 1.5rem;
      margin-bottom: 1.5rem;
      font-weight: bold;
      line-height: 1.4;
      word-break: break-word
    ">
      {{ post?.title || t('postDetail.noTitle') }}
    </h1>
    <div v-if="post?.imageUrl" style="margin-bottom: 1.5rem">
      <img
        :src="post.imageUrl"
        :alt="post.title || 'post image'"
        style="width: 100%; max-height: 360px; object-fit: cover; border-radius: 12px; border: 1px solid #e5e7eb"
      />
    </div>
    <div class="post-body" style="
      margin-bottom: 0;
      padding-bottom: 1rem;
      line-height: 1.8;
      word-break: break-word;
      overflow: visible;
      font-size: 0.9375rem;
      color: #374151;
      position: relative;
      z-index: 0;
      display: block;
      width: 100%;
      clear: both
    ">
      <div v-if="!post?.body || !post.body.trim()" style="
        color: #666;
        font-style: italic;
        padding: 1.5rem;
        background: #f9fafb;
        border-radius: 8px;
        text-align: center;
        border: 2px dashed #d1d5db
      ">
        {{ t('postDetail.noContent') }}
      </div>
      <div v-else v-html="formatContent(post.body)"></div>
    </div>

    <!-- Post Actions -->
    <div style="
      display: flex;
      gap: 1rem;
      padding: 1rem 0;
      border-top: 2px dashed #e5e7eb;
      border-bottom: 2px dashed #e5e7eb;
      margin-top: 2rem;
      margin-bottom: 1.5rem;
      flex-wrap: wrap;
      align-items: center;
      position: relative;
      z-index: 2;
      clear: both;
      width: 100%;
      box-sizing: border-box
    ">
      <button
        class="btn"
        @click="handleToggleLike"
        :style="{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          padding: '0.5rem 1rem',
          background: postDetail.isLiked ? '#fee2e2' : 'transparent',
          color: postDetail.isLiked ? '#dc2626' : 'inherit'
        }"
      >
        <span>{{ postDetail.isLiked ? '❤️' : '🤍' }}</span>
        <span>{{ postDetail.likeCount || 0 }}</span>
      </button>
      <div style="display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem">
        <span>💬</span>
        <span>{{ postDetail.commentCount || 0 }}</span>
      </div>
      <div style="
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem 1rem;
        color: #666;
        font-size: 0.875rem;
        margin-left: auto
      ">
        <span>{{ formatDate(post?.createdAt) }}</span>
      </div>
      <button
        v-if="token"
        class="btn"
        @click="showReportDialog = true"
        style="
          padding: 0.5rem 1rem;
          font-size: 0.875rem;
          background: #fee2e2;
          color: #dc2626;
          border: 1px solid #fecaca;
        "
      >
        🚩 {{ t('postDetail.report') }}
      </button>
    </div>

    <!-- Comment Form -->
    <div v-if="token" style="
      margin-top: 1.5rem;
      margin-bottom: 2rem;
      padding: 1.5rem;
      background: #f9fafb;
      border-radius: 8px;
      border: 2px solid #e5e7eb;
      position: relative;
      z-index: 2;
      clear: both
    ">
      <h3 style="
        margin-bottom: 1rem;
        font-size: 1rem;
        font-weight: bold
      ">
        {{ t('postDetail.addComment') }}
      </h3>
      <textarea
        class="input"
        v-model="commentContent"
        :placeholder="t('postDetail.commentPlaceholder')"
        rows="4"
        style="
          width: 100%;
          margin-bottom: 0.75rem;
          min-height: 100px;
          resize: vertical
        "
      />
      <button
        class="btn btn-primary"
        @click="handleAddComment"
        :disabled="submittingComment || !commentContent.trim()"
        style="min-width: 100px"
      >
        {{ submittingComment ? t('postDetail.submitting') : t('postDetail.submitComment') }}
      </button>
    </div>

    <!-- Comments List -->
    <div>
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #e5e7eb
      ">
        <h3 style="
          font-size: 1.125rem;
          font-weight: bold;
          margin: 0
        ">
          {{ t('postDetail.comments') }} ({{ postDetail.comments?.length || 0 }})
        </h3>
        <button
          v-if="postDetail.comments && postDetail.comments.length > 0"
          class="btn"
          @click="handleGenerateSummary"
          :disabled="loadingSummary"
          style="
            padding: 0.5rem 1rem;
            font-size: 0.875rem;
            background: #f3f4f6;
            border: 1px solid #d1d5db;
            display: flex;
            align-items: center;
            gap: 0.5rem
          "
        >
          <span v-if="loadingSummary">⏳</span>
          <span v-else>🤖</span>
          <span>{{ loadingSummary ? t('postDetail.summarizing') : t('postDetail.summarizeComments') }}</span>
        </button>
      </div>
      
      <!-- Comment Summary Display -->
      <div
        v-if="commentSummary"
        style="
          margin-bottom: 1.5rem;
          padding: 1rem;
          background: #f0f9ff;
          border: 2px solid #3b82f6;
          border-radius: 8px;
          border-left: 4px solid #3b82f6
        "
      >
        <div style="
          display: flex;
          align-items: center;
          gap: 0.5rem;
          margin-bottom: 0.75rem;
          font-weight: bold;
          color: #1e40af;
          font-size: 0.875rem
        ">
          <span>📝</span>
          <span>{{ t('postDetail.commentSummary') }}</span>
          <span style="font-weight: normal; color: #666; font-size: 0.75rem">
            ({{ summaryCommentCount }} {{ t('postDetail.comments') }})
          </span>
        </div>
        <div style="
          line-height: 1.8;
          color: #1e3a8a;
          white-space: pre-wrap;
          word-break: break-word
        ">
          {{ commentSummary }}
        </div>
      </div>
      <div v-if="postDetail.comments && postDetail.comments.length > 0" style="display: flex; flex-direction: column; gap: 1rem">
        <div
          v-for="comment in postDetail.comments"
          :key="comment.id"
          style="
            padding: 1rem;
            background: #fff;
            border-radius: 8px;
            border: 2px solid #e5e7eb;
            transition: all 0.2s
          "
        >
          <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem">
            <div class="post-avatar" style="width: 32px; height: 32px"></div>
            <div>
              <div class="post-author-name" style="font-size: 0.875rem">
                {{ comment.authorDisplayName || comment.authorName || t('postList.anonymous') }}
              </div>
              <div style="font-size: 0.75rem; color: #666">
                {{ formatDate(comment.createdAt) }}
              </div>
            </div>
          </div>
          <div style="display: flex; justify-content: space-between; align-items: flex-start">
            <div style="margin-left: 2.5rem; line-height: 1.6; flex: 1">
              {{ comment.content }}
            </div>
            <div style="display: flex; gap: 0.5rem; margin-left: 1rem">
              <button
                v-if="token && comment.authorId === currentUserId"
                class="btn"
                @click="handleDeleteComment(comment.id)"
                :disabled="deletingCommentId === comment.id"
                style="
                  padding: 0.25rem 0.5rem;
                  font-size: 0.75rem;
                  background: #fee2e2;
                  color: #dc2626;
                  border: 1px solid #fecaca;
                "
              >
                {{ deletingCommentId === comment.id ? t('postDetail.deleting') : t('postDetail.delete') }}
              </button>
              <button
                v-if="token"
                class="btn"
                @click="openCommentReportDialog(comment.id)"
                style="
                  padding: 0.25rem 0.5rem;
                  font-size: 0.75rem;
                  background: #f3f4f6;
                  color: #666;
                  border: 1px solid #d1d5db;
                "
              >
                🚩
              </button>
            </div>
          </div>
        </div>
      </div>
      <p v-else style="color: #666; font-style: italic">{{ t('postDetail.noComments') }}</p>
    </div>

    <!-- Report Dialog -->
    <div
      v-if="showReportDialog"
      style="
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
      "
      @click.self="showReportDialog = false"
    >
      <div
        style="
          background: white;
          padding: 2rem;
          border-radius: 12px;
          max-width: 500px;
          width: 90%;
          max-height: 80vh;
          overflow-y: auto;
        "
      >
        <h3 style="margin-bottom: 1.5rem; font-size: 1.25rem; font-weight: bold">
          {{ t('postDetail.reportPost') }}
        </h3>
        <div style="margin-bottom: 1rem">
          <label style="display: block; margin-bottom: 0.5rem; font-weight: 600">
            {{ t('postDetail.reportReasons') }} <span style="color: #dc2626">*</span>
          </label>
          <div style="display: flex; flex-direction: column; gap: 0.5rem">
            <label
              v-for="reason in reportReasons"
              :key="reason.value"
              style="display: flex; align-items: center; gap: 0.5rem; cursor: pointer"
            >
              <input
                type="checkbox"
                :value="reason.value"
                v-model="selectedReportReasons"
                style="cursor: pointer"
              />
              <span>{{ reason.label }}</span>
            </label>
          </div>
        </div>
        <div style="margin-bottom: 1.5rem">
          <label style="display: block; margin-bottom: 0.5rem; font-weight: 600">
            {{ t('postDetail.reportDescription') }}
          </label>
          <textarea
            v-model="reportDescription"
            :placeholder="t('postDetail.reportDescriptionPlaceholder')"
            rows="4"
            style="
              width: 100%;
              padding: 0.75rem;
              border: 1px solid #d1d5db;
              border-radius: 6px;
              font-family: inherit;
              resize: vertical;
            "
          />
        </div>
        <div style="display: flex; gap: 1rem; justify-content: flex-end">
          <button
            class="btn"
            @click="showReportDialog = false"
            style="padding: 0.75rem 1.5rem"
          >
            {{ t('common.cancel') }}
          </button>
          <button
            class="btn btn-primary"
            @click="handleSubmitReport('POST', postId)"
            :disabled="selectedReportReasons.length === 0 || submittingReport"
            style="padding: 0.75rem 1.5rem"
          >
            {{ submittingReport ? t('postDetail.submitting') : t('postDetail.submitReport') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Comment Report Dialog -->
    <div
      v-if="showCommentReportDialog"
      style="
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
      "
      @click.self="showCommentReportDialog = false"
    >
      <div
        style="
          background: white;
          padding: 2rem;
          border-radius: 12px;
          max-width: 500px;
          width: 90%;
          max-height: 80vh;
          overflow-y: auto;
        "
      >
        <h3 style="margin-bottom: 1.5rem; font-size: 1.25rem; font-weight: bold">
          {{ t('postDetail.reportComment') }}
        </h3>
        <div style="margin-bottom: 1rem">
          <label style="display: block; margin-bottom: 0.5rem; font-weight: 600">
            {{ t('postDetail.reportReasons') }} <span style="color: #dc2626">*</span>
          </label>
          <div style="display: flex; flex-direction: column; gap: 0.5rem">
            <label
              v-for="reason in reportReasons"
              :key="reason.value"
              style="display: flex; align-items: center; gap: 0.5rem; cursor: pointer"
            >
              <input
                type="checkbox"
                :value="reason.value"
                v-model="selectedReportReasons"
                style="cursor: pointer"
              />
              <span>{{ reason.label }}</span>
            </label>
          </div>
        </div>
        <div style="margin-bottom: 1.5rem">
          <label style="display: block; margin-bottom: 0.5rem; font-weight: 600">
            {{ t('postDetail.reportDescription') }}
          </label>
          <textarea
            v-model="reportDescription"
            :placeholder="t('postDetail.reportDescriptionPlaceholder')"
            rows="4"
            style="
              width: 100%;
              padding: 0.75rem;
              border: 1px solid #d1d5db;
              border-radius: 6px;
              font-family: inherit;
              resize: vertical;
            "
          />
        </div>
        <div style="display: flex; gap: 1rem; justify-content: flex-end">
          <button
            class="btn"
            @click="showCommentReportDialog = false; reportTargetId = null"
            style="padding: 0.75rem 1.5rem"
          >
            {{ t('common.cancel') }}
          </button>
          <button
            class="btn btn-primary"
            @click="handleSubmitReport('COMMENT', reportTargetId)"
            :disabled="selectedReportReasons.length === 0 || submittingReport"
            style="padding: 0.75rem 1.5rem"
          >
            {{ submittingReport ? t('postDetail.submitting') : t('postDetail.submitReport') }}
          </button>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue';
import { fetchPostDetail, addComment, toggleLike, toggleFollow, getCommentSummary, deleteComment, submitReport } from '../api';
import { getCurrentLanguage, t } from '../i18n';

// Filter out browser extension errors
if (typeof window !== 'undefined') {
  const originalError = console.error;
  console.error = (...args) => {
    const errorMsg = args.join(' ');
    if (errorMsg.includes('content-all.js') || 
        errorMsg.includes('chrome-extension') ||
        errorMsg.includes('Could not establish connection') ||
        errorMsg.includes('Receiving end does not exist')) {
      return;
    }
    originalError.apply(console, args);
  };
}

const props = defineProps({
  postId: {
    type: [String, Number],
    required: true
  },
  token: {
    type: String,
    default: null
  },
  currentUserId: {
    type: [String, Number],
    default: null
  },
  onBack: {
    type: Function,
    default: null
  }
});

const postDetail = ref(null);
const loading = ref(true);
const error = ref(null);
const commentContent = ref('');
const submittingComment = ref(false);
const lang = ref(getCurrentLanguage());
const commentSummary = ref(null);
const loadingSummary = ref(false);
const summaryCommentCount = ref(0);
const showReportDialog = ref(false);
const showCommentReportDialog = ref(false);
const reportTargetId = ref(null);
const selectedReportReasons = ref([]);
const reportDescription = ref('');
const submittingReport = ref(false);
const deletingCommentId = ref(null);

// Report reasons
const reportReasons = computed(() => {
  const langValue = lang.value || 'en';
  if (langValue === 'zh') {
    return [
      { value: 'Spam', label: '垃圾信息' },
      { value: 'Fraud or Scam', label: '欺诈或诈骗' },
      { value: 'Illegal Service Promotion', label: '非法服务推广' },
      { value: 'Abusive Language', label: '辱骂性语言' },
      { value: 'Other', label: '其他' }
    ];
  }
  return [
    { value: 'Spam', label: 'Spam' },
    { value: 'Fraud or Scam', label: 'Fraud or Scam' },
    { value: 'Illegal Service Promotion', label: 'Illegal Service Promotion' },
    { value: 'Abusive Language', label: 'Abusive Language' },
    { value: 'Other', label: 'Other' }
  ];
});

const post = computed(() => postDetail.value?.post);

const formatDate = (dateString) => {
  if (!dateString) return '';
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now - date;
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return t('postDetail.justNow');
  if (diffMins < 60) return `${diffMins}${t('postDetail.minutesAgo')}`;
  if (diffHours < 24) return `${diffHours}${t('postDetail.hoursAgo')}`;
  if (diffDays < 7) return `${diffDays}${t('postDetail.daysAgo')}`;
  return date.toLocaleDateString();
};

const formatContent = (text) => {
  if (!text) return '';
  
  // 简单的 Markdown 格式化
  let formatted = text;
  
  // 处理行内粗体 **text**
  formatted = formatted.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  
  // 处理分隔线
  formatted = formatted.replace(/^---+$/gm, '<hr style="border: none; border-top: 2px dashed #d1d5db; margin: 1.5rem 0; background: none" />');
  
  // 处理标题行
  formatted = formatted.replace(/^\*\*(.+?)\*\*$/gm, '<h3 style="font-size: 1rem; font-weight: bold; margin-top: 1.5rem; margin-bottom: 0.75rem; color: #111827">$1</h3>');
  
  // 处理链接
  formatted = formatted.replace(/(🔗)\s*\*\*(.+?)\*\*:\s*(.+)/g, (match, emoji, linkText, linkUrl) => {
    const isUrl = linkUrl.trim().match(/^https?:\/\//);
    if (isUrl) {
      return `<div style="margin-top: 1.5rem; margin-bottom: 2rem; padding: 0.75rem 1rem; background: #f9fafb; border-radius: 6px; border-left: 3px solid #3b82f6; position: relative; z-index: 1; display: block; width: 100%; box-sizing: border-box; clear: both">
        <div style="font-weight: bold; margin-bottom: 0.5rem; font-size: 0.875rem; color: #374151; display: block; width: 100%">
          🔗 ${linkText}:
        </div>
        <a href="${linkUrl.trim()}" target="_blank" rel="noopener noreferrer" style="color: #2563eb; text-decoration: underline; word-break: break-all; font-size: 0.875rem; display: inline-block; width: 100%; max-width: 100%; overflow-wrap: break-word">
          ${linkUrl.trim()}
        </a>
      </div>`;
    } else {
      return `<div style="margin-top: 1.5rem; margin-bottom: 2rem; padding: 0.75rem 1rem; background: #f9fafb; border-radius: 6px; border-left: 3px solid #3b82f6; position: relative; z-index: 1; display: block; width: 100%; box-sizing: border-box; clear: both">
        <div style="font-weight: bold; margin-bottom: 0.5rem; font-size: 0.875rem; color: #374151; display: block; width: 100%">
          🔗 ${linkText}:
        </div>
        <span style="font-size: 0.875rem; color: #6b7280; display: block; word-break: break-word">
          ${linkUrl.trim()}
        </span>
      </div>`;
    }
  });
  
  // 分割成段落
  const paragraphs = formatted.split(/\n\s*\n/).filter(p => p.trim());
  return paragraphs.map(p => `<p style="margin-top: 1rem; margin-bottom: 0.75rem; line-height: 1.8; position: relative; z-index: 0; display: block; width: 100%; clear: both">${p.trim()}</p>`).join('');
};

const loadPostDetail = async () => {
  if (!props.postId) return;
  
  loading.value = true;
  error.value = null;
  try {
    const savedLang = localStorage.getItem('userLanguage');
    const currentLang = getCurrentLanguage();
    const langToUse = lang.value || savedLang || currentLang || 'en';
    
    console.log('🔍 PostDetail: Loading post detail', { 
      postId: props.postId, 
      langToUse,
      lang: lang.value,
      savedLang,
      currentLang,
      'localStorage.userLanguage': localStorage.getItem('userLanguage')
    });
    const data = await fetchPostDetail(props.postId, langToUse);
    console.log('📦 PostDetail: Received data:', {
      hasPost: !!data.post,
      postTitle: data.post?.title,
      postTitleLength: data.post?.title?.length || 0,
      postBody: data.post?.body ? `${data.post.body.substring(0, 100)}...` : 'EMPTY',
      postBodyLength: data.post?.body?.length || 0,
      hasContentZh: !!data.post?.contentZh,
      hasContentEn: !!data.post?.contentEn,
      'requestedLang': langToUse,
      fullData: data
    });
    postDetail.value = data;
  } catch (err) {
    console.error('Failed to load post detail:', err);
    error.value = 'Failed to load post';
  } finally {
    loading.value = false;
  }
};

const handleAddComment = async () => {
  if (!commentContent.value.trim() || !props.token) {
    return;
  }

  submittingComment.value = true;
  try {
    const savedLang = localStorage.getItem('userLanguage');
    const currentLang = getCurrentLanguage();
    const langToUse = lang.value || savedLang || currentLang || 'en';
    
    await addComment(props.postId, commentContent.value, langToUse, props.token);
    commentContent.value = '';
    // Clear summary when new comment is added
    commentSummary.value = null;
    summaryCommentCount.value = 0;
    await loadPostDetail();
  } catch (err) {
    console.error('Failed to add comment:', err);
    alert(t('postDetail.commentFailed'));
  } finally {
    submittingComment.value = false;
  }
};

const handleGenerateSummary = async () => {
  if (!props.postId || !postDetail.value?.comments || postDetail.value.comments.length === 0) {
    return;
  }

  loadingSummary.value = true;
  try {
    const savedLang = localStorage.getItem('userLanguage');
    const currentLang = getCurrentLanguage();
    const langToUse = lang.value || savedLang || currentLang || 'en';
    
    const response = await getCommentSummary(props.postId, langToUse);
    
    if (response.summary) {
      commentSummary.value = response.summary;
      summaryCommentCount.value = response.commentCount || 0;
    } else if (response.error) {
      alert(response.message || response.error);
    }
  } catch (err) {
    console.error('Failed to generate comment summary:', err);
    alert(t('postDetail.summaryFailed') || 'Failed to generate comment summary');
  } finally {
    loadingSummary.value = false;
  }
};

const handleToggleLike = async () => {
  if (!props.token) {
    alert(t('postDetail.loginRequired'));
    return;
  }

  try {
    const result = await toggleLike(props.postId, props.token);
    postDetail.value = {
      ...postDetail.value,
      isLiked: result.liked,
      likeCount: result.likeCount
    };
  } catch (err) {
    console.error('Failed to toggle like:', err);
  }
};

const handleDeleteComment = async (commentId) => {
  if (!confirm(t('postDetail.confirmDeleteComment'))) {
    return;
  }
  
  deletingCommentId.value = commentId;
  try {
    await deleteComment(props.postId, commentId, props.token);
    // Reload post detail to refresh comments
    await loadPostDetail();
    alert(t('postDetail.commentDeleted'));
  } catch (err) {
    console.error('Failed to delete comment:', err);
    alert(err.response?.data?.message || t('postDetail.commentDeleteFailed'));
  } finally {
    deletingCommentId.value = null;
  }
};

const openCommentReportDialog = (commentId) => {
  reportTargetId.value = commentId;
  selectedReportReasons.value = [];
  reportDescription.value = '';
  showCommentReportDialog.value = true;
};

const handleSubmitReport = async (targetType, targetId) => {
  if (!targetId || selectedReportReasons.value.length === 0) {
    return;
  }
  
  submittingReport.value = true;
  try {
    await submitReport(targetType, targetId, selectedReportReasons.value, reportDescription.value, props.token);
    alert(t('postDetail.reportSubmitted'));
    showReportDialog.value = false;
    showCommentReportDialog.value = false;
    reportTargetId.value = null;
    selectedReportReasons.value = [];
    reportDescription.value = '';
  } catch (err) {
    console.error('Failed to submit report:', err);
    alert(err.response?.data?.message || t('postDetail.reportFailed'));
  } finally {
    submittingReport.value = false;
  }
};

const handleToggleFollow = async () => {
  if (!props.token) {
    alert(t('postDetail.loginRequired'));
    return;
  }

  if (!postDetail.value || !postDetail.value.authorId) {
    return;
  }

  try {
    const result = await toggleFollow(postDetail.value.authorId, props.token);
    postDetail.value = {
      ...postDetail.value,
      isFollowing: result.following
    };
  } catch (err) {
    console.error('Failed to toggle follow:', err);
  }
};

onMounted(() => {
  const savedLang = localStorage.getItem('userLanguage');
  const currentLang = getCurrentLanguage();
  const langToSet = (savedLang === 'zh' || savedLang === 'en') ? savedLang : (currentLang || 'en');
  lang.value = langToSet;
  
  const handleLanguageChange = (e) => {
    if (e && e.detail && e.detail.lang) {
      console.log('PostDetail: Language changed to:', e.detail.lang);
      const previousLang = lang.value;
      lang.value = e.detail.lang;
      
      // 如果对话框是打开的，保持打开状态，只更新翻译文本
      // 不触发数据重新加载，避免对话框闪烁
      if (showReportDialog.value || showCommentReportDialog.value) {
        // 对话框打开时，只更新UI，不重新加载数据
        return;
      }
      
      // 只有在对话框关闭时才重新加载数据
      if (props.postId && previousLang !== lang.value) {
        // 延迟加载，避免频繁请求
        setTimeout(() => {
          if (!showReportDialog.value && !showCommentReportDialog.value) {
            loadPostDetail();
          }
        }, 100);
      }
    }
  };
  
  if (typeof window !== 'undefined') {
    window.addEventListener('languageChanged', handleLanguageChange);
  }
  
  loadPostDetail();
  
  return () => {
    if (typeof window !== 'undefined') {
      window.removeEventListener('languageChanged', handleLanguageChange);
    }
  };
});

watch(() => props.postId, () => {
  if (props.postId) {
    loadPostDetail();
  }
});

watch(lang, () => {
  // 当语言变化时，如果对话框没有打开，才重新加载数据
  // 这样可以避免对话框在语言切换时关闭和闪烁
  if (props.postId && !showReportDialog.value && !showCommentReportDialog.value) {
    loadPostDetail();
  }
});
</script>

<style scoped>
/* Styles are in styles.css */
</style>

// frontend/src/components/PostDetail.jsx
import { useEffect, useState } from 'react';
import { fetchPostDetail, addComment, toggleLike, toggleFollow } from '../api';
import { getCurrentLanguage, t } from '../i18n';

// Filter out browser extension errors
if (typeof window !== 'undefined') {
  const originalError = console.error;
  console.error = (...args) => {
    const errorMsg = args.join(' ');
    // Filter out browser extension errors
    if (errorMsg.includes('content-all.js') || 
        errorMsg.includes('chrome-extension') ||
        errorMsg.includes('Could not establish connection') ||
        errorMsg.includes('Receiving end does not exist')) {
      return; // Ignore these errors
    }
    originalError.apply(console, args);
  };
}

const PostDetail = ({ postId, token, currentUserId, onBack }) => {
  const [postDetail, setPostDetail] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [commentContent, setCommentContent] = useState('');
  const [submittingComment, setSubmittingComment] = useState(false);
  const [lang, setLang] = useState(getCurrentLanguage());

  useEffect(() => {
    const savedLang = localStorage.getItem('userLanguage');
    const currentLang = getCurrentLanguage();
    const langToSet = (savedLang === 'zh' || savedLang === 'en') ? savedLang : (currentLang || 'en');
    setLang(langToSet);
  }, []);

  // Listen for language changes
  useEffect(() => {
    const handleLanguageChange = (e) => {
      if (e && e.detail && e.detail.lang) {
        console.log('PostDetail: Language changed to:', e.detail.lang);
        setLang(e.detail.lang);
      }
    };
    
    if (typeof window !== 'undefined') {
      window.addEventListener('languageChanged', handleLanguageChange);
      return () => {
        window.removeEventListener('languageChanged', handleLanguageChange);
      };
    }
  }, []);

  useEffect(() => {
    if (postId) {
      loadPostDetail();
    }
  }, [postId, lang]);

  const loadPostDetail = async () => {
    if (!postId) return;
    
    setLoading(true);
    setError(null);
    try {
      const savedLang = localStorage.getItem('userLanguage');
      const currentLang = getCurrentLanguage();
      const langToUse = lang || savedLang || currentLang || 'en';
      
      console.log('🔍 PostDetail: Loading post detail', { 
        postId, 
        langToUse,
        lang,
        savedLang,
        currentLang,
        'localStorage.userLanguage': localStorage.getItem('userLanguage')
      });
      const data = await fetchPostDetail(postId, langToUse);
      console.log('📦 PostDetail: Received data:', {
        hasPost: !!data.post,
        postTitle: data.post?.title,
        postTitleLength: data.post?.title?.length || 0,
        postBody: data.post?.body ? `${data.post.body.substring(0, 100)}...` : 'EMPTY',
        postBodyLength: data.post?.body?.length || 0,
        hasContentZh: !!data.post?.contentZh,
        hasContentEn: !!data.post?.contentEn,
        'requestedLang': langToUse,
        fullData: data
      });
      setPostDetail(data);
    } catch (err) {
      console.error('Failed to load post detail:', err);
      setError('Failed to load post');
    } finally {
      setLoading(false);
    }
  };

  const handleAddComment = async () => {
    if (!commentContent.trim() || !token) {
      return;
    }

    setSubmittingComment(true);
    try {
      const savedLang = localStorage.getItem('userLanguage');
      const currentLang = getCurrentLanguage();
      const langToUse = lang || savedLang || currentLang || 'en';
      
      await addComment(postId, commentContent, langToUse, token);
      setCommentContent('');
      // Reload post detail to get updated comments
      await loadPostDetail();
    } catch (err) {
      console.error('Failed to add comment:', err);
      alert(t('postDetail.commentFailed'));
    } finally {
      setSubmittingComment(false);
    }
  };

  const handleToggleLike = async () => {
    if (!token) {
      alert(t('postDetail.loginRequired'));
      return;
    }

    try {
      const result = await toggleLike(postId, token);
      // Update local state
      setPostDetail(prev => ({
        ...prev,
        isLiked: result.liked,
        likeCount: result.likeCount
      }));
    } catch (err) {
      console.error('Failed to toggle like:', err);
    }
  };

  const handleToggleFollow = async () => {
    if (!token) {
      alert(t('postDetail.loginRequired'));
      return;
    }

    if (!postDetail || !postDetail.authorId) {
      return;
    }

    try {
      const result = await toggleFollow(postDetail.authorId, token);
      // Update local state
      setPostDetail(prev => ({
        ...prev,
        isFollowing: result.following
      }));
    } catch (err) {
      console.error('Failed to toggle follow:', err);
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now - date;
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return t('postDetail.justNow');
    if (diffMins < 60) return `${diffMins}${t('postDetail.minutesAgo')}`;
    if (diffHours < 24) return `${diffHours}${t('postDetail.hoursAgo')}`;
    if (diffDays < 7) return `${diffDays}${t('postDetail.daysAgo')}`;
    return date.toLocaleDateString();
  };

  if (loading) {
    return (
      <section className="card">
        <p>{t('postDetail.loading')}</p>
      </section>
    );
  }

  if (error || !postDetail) {
    return (
      <section className="card">
        <p style={{ color: '#dc2626' }}>{error || t('postDetail.notFound')}</p>
        {onBack && (
          <button className="btn" onClick={onBack}>
            {t('postDetail.back')}
          </button>
        )}
      </section>
    );
  }

  const post = postDetail.post;

  return (
    <section className="card">
      {onBack && (
        <div style={{ marginBottom: '1rem' }}>
          <button className="btn" onClick={onBack} style={{ marginBottom: '1rem' }}>
            ← {t('postDetail.back')}
          </button>
        </div>
      )}

      {/* Post Header */}
      <div className="post-header" style={{ marginBottom: '1rem', paddingBottom: '1rem', borderBottom: '1px solid #e5e7eb' }}>
        <div className="post-author" style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div className="post-avatar"></div>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <div className="post-author-name">{postDetail.authorDisplayName || postDetail.authorName || t('postList.anonymous')}</div>
              <span className="post-author-badge">{t('postList.student')}</span>
            </div>
            <div style={{ fontSize: '0.875rem', color: '#666', marginTop: '0.25rem' }}>
              @{postDetail.authorName}
            </div>
          </div>
          {currentUserId && postDetail.authorId && currentUserId !== postDetail.authorId && (
            <button
              className={`btn ${postDetail.isFollowing ? '' : 'btn-primary'}`}
              onClick={handleToggleFollow}
              style={{ padding: '0.5rem 1rem', fontSize: '0.875rem' }}
            >
              {postDetail.isFollowing ? t('postDetail.following') : t('postDetail.follow')}
            </button>
          )}
        </div>
      </div>

      {/* Post Content */}
      <h1 className="post-title" style={{ 
        fontSize: '1.5rem', 
        marginBottom: '1.5rem',
        fontWeight: 'bold',
        lineHeight: '1.4',
        wordBreak: 'break-word'
      }}>
        {post.title || t('postDetail.noTitle')}
      </h1>
      {post.imageUrl && (
        <div style={{ marginBottom: '1.5rem' }}>
          <img
            src={post.imageUrl}
            alt={post.title || 'post image'}
            style={{ width: '100%', maxHeight: '360px', objectFit: 'cover', borderRadius: '12px', border: '1px solid #e5e7eb' }}
          />
        </div>
      )}
      <div className="post-body" style={{ 
        marginBottom: '0',
        paddingBottom: '1rem',
        lineHeight: '1.8',
        wordBreak: 'break-word',
        overflow: 'visible',
        fontSize: '0.9375rem',
        color: '#374151',
        position: 'relative',
        zIndex: 0,
        display: 'block',
        width: '100%',
        clear: 'both'
      }}>
        {(() => {
          console.log('🔍 PostDetail render - post.body:', {
            exists: !!post.body,
            length: post.body?.length || 0,
            preview: post.body ? post.body.substring(0, 200) : 'EMPTY',
            trimmed: post.body?.trim() || ''
          });
          
          if (post.body && post.body.trim()) {
            // 简单的 Markdown 格式化函数
            const formatContent = (text) => {
              if (!text) return '';
              
              // 分割成段落
              const paragraphs = text.split(/\n\s*\n/).filter(p => p.trim());
              
              return paragraphs.map((para, idx) => {
                let formatted = para.trim();
                
                // 处理分隔线
                if (formatted.match(/^---+$/)) {
                  return <hr key={idx} style={{ 
                    border: 'none', 
                    borderTop: '2px dashed #d1d5db', 
                    margin: '1.5rem 0',
                    background: 'none'
                  }} />;
                }
                
                // 处理标题行（**Title** 格式）
                const titleMatch = formatted.match(/^(\*\*)(.+?)(\*\*)$/);
                if (titleMatch) {
                  return (
                    <h3 key={idx} style={{
                      fontSize: '1rem',
                      fontWeight: 'bold',
                      marginTop: idx > 0 ? '1.5rem' : '0',
                      marginBottom: '0.75rem',
                      color: '#111827'
                    }}>
                      {titleMatch[2]}
                    </h3>
                  );
                }
                
                // 处理行内粗体 **text**
                formatted = formatted.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
                
                // 处理链接 🔗 **Read Original**: URL 或 🔗 **Source**: text
                const linkMatch = formatted.match(/(🔗)\s*\*\*(.+?)\*\*:\s*(.+)/);
                if (linkMatch) {
                  const linkText = linkMatch[2];
                  const linkUrl = linkMatch[3].trim();
                  const isUrl = linkUrl.match(/^https?:\/\//);
                  
                  return (
                    <div key={idx} style={{
                      marginTop: idx > 0 ? '1.5rem' : '0',
                      marginBottom: '2rem',
                      padding: '0.75rem 1rem',
                      background: '#f9fafb',
                      borderRadius: '6px',
                      borderLeft: '3px solid #3b82f6',
                      position: 'relative',
                      zIndex: 1,
                      display: 'block',
                      width: '100%',
                      boxSizing: 'border-box',
                      clear: 'both'
                    }}>
                      <div style={{ 
                        fontWeight: 'bold', 
                        marginBottom: '0.5rem',
                        fontSize: '0.875rem',
                        color: '#374151',
                        display: 'block',
                        width: '100%'
                      }}>
                        🔗 {linkText}:
                      </div>
                      {isUrl ? (
                        <a 
                          href={linkUrl} 
                          target="_blank" 
                          rel="noopener noreferrer"
                          style={{
                            color: '#2563eb',
                            textDecoration: 'underline',
                            wordBreak: 'break-all',
                            fontSize: '0.875rem',
                            display: 'inline-block',
                            width: '100%',
                            maxWidth: '100%',
                            overflowWrap: 'break-word'
                          }}
                        >
                          {linkUrl}
                        </a>
                      ) : (
                        <span style={{ 
                          fontSize: '0.875rem', 
                          color: '#6b7280',
                          display: 'block',
                          wordBreak: 'break-word'
                        }}>
                          {linkUrl}
                        </span>
                      )}
                    </div>
                  );
                }
                
                // 普通段落
                return (
                  <p 
                    key={idx} 
                    style={{
                      marginTop: idx > 0 ? '1rem' : '0',
                      marginBottom: '0.75rem',
                      lineHeight: '1.8',
                      position: 'relative',
                      zIndex: 0,
                      display: 'block',
                      width: '100%',
                      clear: 'both'
                    }}
                    dangerouslySetInnerHTML={{ __html: formatted }}
                  />
                );
              });
            };
            
            return formatContent(post.body);
          } else {
            console.warn('⚠️ PostDetail: post.body is empty or null', {
              postId: post.id,
              title: post.title,
              body: post.body,
              contentZh: post.contentZh,
              contentEn: post.contentEn
            });
            return (
              <div style={{ 
                color: '#666', 
                fontStyle: 'italic', 
                padding: '1.5rem', 
                background: '#f9fafb', 
                borderRadius: '8px',
                textAlign: 'center',
                border: '2px dashed #d1d5db'
              }}>
                {t('postDetail.noContent')}
              </div>
            );
          }
        })()}
      </div>

      {/* Post Actions */}
      <div style={{ 
        display: 'flex', 
        gap: '1rem', 
        padding: '1rem 0', 
        borderTop: '2px dashed #e5e7eb', 
        borderBottom: '2px dashed #e5e7eb', 
        marginTop: '2rem',
        marginBottom: '1.5rem',
        flexWrap: 'wrap',
        alignItems: 'center',
        position: 'relative',
        zIndex: 2,
        clear: 'both',
        width: '100%',
        boxSizing: 'border-box'
      }}>
        <button
          className="btn"
          onClick={handleToggleLike}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            padding: '0.5rem 1rem',
            background: postDetail.isLiked ? '#fee2e2' : 'transparent',
            color: postDetail.isLiked ? '#dc2626' : 'inherit'
          }}
        >
          <span>{postDetail.isLiked ? '❤️' : '🤍'}</span>
          <span>{postDetail.likeCount || 0}</span>
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem' }}>
          <span>💬</span>
          <span>{postDetail.commentCount || 0}</span>
        </div>
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          gap: '0.5rem', 
          padding: '0.5rem 1rem', 
          color: '#666', 
          fontSize: '0.875rem',
          marginLeft: 'auto'
        }}>
          <span>{formatDate(post.createdAt)}</span>
        </div>
      </div>

      {/* Comment Form */}
      {token && (
        <div style={{ 
          marginTop: '1.5rem',
          marginBottom: '2rem',
          padding: '1.5rem',
          background: '#f9fafb',
          borderRadius: '8px',
          border: '2px solid #e5e7eb',
          position: 'relative',
          zIndex: 2,
          clear: 'both'
        }}>
          <h3 style={{ 
            marginBottom: '1rem',
            fontSize: '1rem',
            fontWeight: 'bold'
          }}>
            {t('postDetail.addComment')}
          </h3>
          <textarea
            className="input"
            value={commentContent}
            onChange={(e) => setCommentContent(e.target.value)}
            placeholder={t('postDetail.commentPlaceholder')}
            rows={4}
            style={{ 
              width: '100%', 
              marginBottom: '0.75rem',
              minHeight: '100px',
              resize: 'vertical'
            }}
          />
          <button
            className="btn btn-primary"
            onClick={handleAddComment}
            disabled={submittingComment || !commentContent.trim()}
            style={{ minWidth: '100px' }}
          >
            {submittingComment ? t('postDetail.submitting') : t('postDetail.submitComment')}
          </button>
        </div>
      )}

      {/* Comments List */}
      <div>
        <h3 style={{ 
          marginBottom: '1rem',
          fontSize: '1.125rem',
          fontWeight: 'bold',
          paddingBottom: '0.5rem',
          borderBottom: '2px solid #e5e7eb'
        }}>
          {t('postDetail.comments')} ({postDetail.comments?.length || 0})
        </h3>
        {postDetail.comments && postDetail.comments.length > 0 ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {postDetail.comments.map((comment) => (
              <div key={comment.id} style={{ 
                padding: '1rem', 
                background: '#fff', 
                borderRadius: '8px',
                border: '2px solid #e5e7eb',
                transition: 'all 0.2s'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                  <div className="post-avatar" style={{ width: '32px', height: '32px' }}></div>
                  <div>
                    <div className="post-author-name" style={{ fontSize: '0.875rem' }}>
                      {comment.authorDisplayName || comment.authorName || t('postList.anonymous')}
                    </div>
                    <div style={{ fontSize: '0.75rem', color: '#666' }}>
                      {formatDate(comment.createdAt)}
                    </div>
                  </div>
                </div>
                <div style={{ marginLeft: '2.5rem', lineHeight: '1.6' }}>
                  {comment.content}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p style={{ color: '#666', fontStyle: 'italic' }}>{t('postDetail.noComments')}</p>
        )}
      </div>
    </section>
  );
};

export default PostDetail;
