// frontend/src/App.jsx
import { useState, useEffect } from 'react';
import LoginPage from './components/LoginPage';
import Sidebar from './components/Sidebar';
import PostList from './components/PostList';
import PostDetail from './components/PostDetail';
import SearchPanel from './components/SearchPanel';
import DailyBriefing from './components/DailyBriefing';
import NlpAssistant from './components/NlpAssistant';
import NewPostForm from './components/NewPostForm';
import AdminPanel from './components/AdminPanel';
import { fetchMyRejectedPosts } from './api';
import { setLanguagePreference, getLanguagePreference } from './utils/language';
import { setLanguage, getCurrentLanguage } from './i18n';

// 从 localStorage 恢复登录状态
const getInitialAuthState = () => {
  try {
    const savedToken = localStorage.getItem('token');
    const savedUser = localStorage.getItem('user');
    if (savedToken && savedUser) {
      return {
        isLoggedIn: true,
        token: savedToken,
        user: JSON.parse(savedUser)
      };
    }
  } catch (e) {
    console.error('Failed to restore auth state:', e);
  }
  return { isLoggedIn: false, token: null, user: null };
};

const App = () => {
  const initialAuth = getInitialAuthState();
  const [isLoggedIn, setIsLoggedIn] = useState(initialAuth.isLoggedIn);
  const [currentPage, setCurrentPage] = useState('home');
  const [selectedPostId, setSelectedPostId] = useState(null);
  const [user, setUser] = useState(initialAuth.user);
  const [token, setToken] = useState(initialAuth.token);
  const [lang, setLang] = useState(getCurrentLanguage());
  const [selectedTag, setSelectedTag] = useState('all');
  const [rejectedPosts, setRejectedPosts] = useState([]);

  // 监听语言变化事件，强制重新渲染整个应用
  useEffect(() => {
    const handleLanguageChange = (e) => {
      if (e && e.detail && e.detail.lang) {
        console.log('App: Language changed to:', e.detail.lang);
        setLang(e.detail.lang);
      }
    };
    
    window.addEventListener('languageChanged', handleLanguageChange);
    return () => {
      window.removeEventListener('languageChanged', handleLanguageChange);
    };
  }, []);

  // 页面关闭时清除登录状态（可选：如果希望关闭浏览器标签页时登出）
  useEffect(() => {
    // 标记当前会话为活跃
    sessionStorage.setItem('sessionActive', 'true');
    
    // 监听页面关闭事件
    const handleBeforeUnload = () => {
      // 检查是否是刷新（sessionStorage 在刷新时保留）
      // 如果 sessionStorage 中没有 sessionActive，说明是新标签页
    };
    
    // 检查是否是从关闭的标签页恢复（新会话）
    const wasSessionActive = sessionStorage.getItem('sessionActive');
    if (!wasSessionActive && initialAuth.isLoggedIn) {
      // 这是一个新会话（浏览器重新打开），清除登录状态
      console.log('App: New session detected, clearing auth state');
      localStorage.removeItem('token');
      localStorage.removeItem('user');
      setIsLoggedIn(false);
      setUser(null);
      setToken(null);
    }
    
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, []);

  // 恢复登录后设置语言
  useEffect(() => {
    if (isLoggedIn && user?.preferredLanguage) {
      const userLang = user.preferredLanguage;
      if (userLang === 'zh' || userLang === 'en') {
        setLanguagePreference(userLang);
        setLanguage(userLang);
      }
    }
  }, [isLoggedIn, user]);

  const handleLogin = (userData, authToken) => {
    console.log('App: handleLogin called, userData:', userData);
    setIsLoggedIn(true);
    setUser(userData);
    setToken(authToken);
    // 保存 token 到 localStorage，方便其他工具使用
    if (authToken) {
      localStorage.setItem('token', authToken);
      console.log('App: Token saved to localStorage');
    }
    if (userData) {
      localStorage.setItem('user', JSON.stringify(userData));
    }
    setCurrentPage('home');
    
    // 从用户信息中读取语言偏好并设置（作为备用，LoginPage 应该已经设置了）
    if (userData && userData.preferredLanguage) {
      const userLang = userData.preferredLanguage;
      console.log('App: User preferredLanguage:', userLang);
      if (userLang === 'zh' || userLang === 'en') {
        console.log('App: Setting language to:', userLang);
        setLanguagePreference(userLang);
        setLanguage(userLang);
        console.log('App: Language set, localStorage:', localStorage.getItem('userLanguage'));
      }
    } else {
      console.warn('App: No preferredLanguage in userData, checking localStorage...');
      const savedLang = localStorage.getItem('userLanguage');
      if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
        console.log('App: Using saved language from localStorage:', savedLang);
        setLanguage(savedLang);
      }
    }
  };

  const handleNavigate = (page, postId = null) => {
    if (page === 'logout') {
      setIsLoggedIn(false);
      setUser(null);
      setToken(null);
      // 清除 localStorage 和 sessionStorage 中的登录数据
      localStorage.removeItem('token');
      localStorage.removeItem('user');
      sessionStorage.removeItem('sessionActive');
      return;
    }
    if (page === 'postDetail' && postId) {
      setSelectedPostId(postId);
      setCurrentPage('postDetail');
    } else {
      setCurrentPage(page);
      setSelectedPostId(null);
    }
  };

  const isAdmin = user?.role === 'ADMIN';

  // 加载当前用户被拒绝的帖子（用于个人页面显示审核结果）
  useEffect(() => {
    const loadRejected = async () => {
      try {
        if (!token) return;
        const data = await fetchMyRejectedPosts();
        setRejectedPosts(Array.isArray(data) ? data : []);
      } catch (e) {
        console.error('Failed to load rejected posts', e);
      }
    };
    loadRejected();
  }, [token]);

  const renderMainContent = () => {
    switch (currentPage) {
      case 'home':
        return (
          <>
            <DailyBriefing key={`briefing-${lang}`} />
            <div className="section-title" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span>{lang === 'zh' ? '社区动态' : 'Community Feed'}</span>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <span
                  className={`pill ${selectedTag === 'all' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('all')}
                  style={{ cursor: 'pointer' }}
                >
                  {lang === 'zh' ? '全部' : 'All'}
                </span>
                <span
                  className={`pill ${selectedTag === 'rent' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('rent')}
                  style={{ cursor: 'pointer' }}
                >
                  🏠 #{lang === 'zh' ? '租房' : 'Rent'}
                </span>
                <span
                  className={`pill ${selectedTag === 'learning' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('learning')}
                  style={{ cursor: 'pointer' }}
                >
                  📚 #{lang === 'zh' ? '学习' : 'Learning'}
                </span>
                <span
                  className={`pill ${selectedTag === 'market' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('market')}
                  style={{ cursor: 'pointer' }}
                >
                  🛒 #{lang === 'zh' ? '市场' : 'Market'}
                </span>
                <span
                  className={`pill ${selectedTag === 'visa' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('visa')}
                  style={{ cursor: 'pointer' }}
                >
                  🛂 #{lang === 'zh' ? '签证' : 'Visa'}
                </span>
                <span
                  className={`pill ${selectedTag === 'food' ? 'active' : ''}`}
                  onClick={() => setSelectedTag('food')}
                  style={{ cursor: 'pointer' }}
                >
                  🍜 #{lang === 'zh' ? '美食' : 'Food'}
                </span>
              </div>
            </div>
            <PostList
              key={`posts-${lang}`}
              onPostClick={(postId) => handleNavigate('postDetail', postId)}
              selectedTag={selectedTag}
            />
          </>
        );
      case 'post':
        return <NewPostForm key={`newpost-${lang}`} currentUserId={user?.id} />;
      case 'search':
        return <SearchPanel key={`search-${lang}`} />;
      case 'assistant':
        return <NlpAssistant key={`assistant-${lang}`} />;
      case 'admin':
        return isAdmin ? <AdminPanel key={`admin-${lang}`} token={token} /> : <div className="card">{lang === 'zh' ? '无权访问' : 'Access Denied'}</div>;
      case 'postDetail':
        return selectedPostId ? (
          <PostDetail key={`detail-${lang}-${selectedPostId}`} postId={selectedPostId} token={token} currentUserId={user?.id} onBack={() => handleNavigate('home')} />
        ) : (
          <div className="card">{lang === 'zh' ? '帖子未找到' : 'Post not found'}</div>
        );
      case 'profile':
        return (
          <div className="card">
            <h2 className="section-title">Profile</h2>
            <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '1rem' }}>
              <div style={{
                width: '80px',
                height: '80px',
                borderRadius: '50%',
                border: '2px solid #333',
                background: '#e0e0e0',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '2rem'
              }}>👤</div>
              <div>
                <h3 style={{ margin: 0 }}>Chen</h3>
                <p style={{ margin: '4px 0', color: '#666', fontFamily: 'monospace' }}>@chen_student</p>
                <span className="pill">Chinese Student</span>
              </div>
            </div>
            <p style={{ fontFamily: 'Georgia, serif' }}>Freshman at CMU. Looking for a quiet condo near Nimman. Love spicy food! 🌶️</p>
            <div style={{ display: 'flex', gap: '2rem', padding: '1rem 0', borderTop: '2px dashed #333', borderBottom: '2px dashed #333', margin: '1rem 0' }}>
              <div style={{ textAlign: 'center' }}><strong style={{ fontSize: '1.25rem' }}>12</strong><br /><small>Posts</small></div>
              <div style={{ textAlign: 'center' }}><strong style={{ fontSize: '1.25rem' }}>24</strong><br /><small>Following</small></div>
              <div style={{ textAlign: 'center' }}><strong style={{ fontSize: '1.25rem' }}>8</strong><br /><small>Followers</small></div>
            </div>
            {/* 审核结果区域：展示被拒绝的帖子及理由 */}
            <div style={{ marginTop: '1rem' }}>
              <h3 className="section-title" style={{ fontSize: '1rem' }}>
                {lang === 'zh' ? '被拒绝的帖子与审核理由' : 'Rejected Posts & Review Notes'}
              </h3>
              {(!rejectedPosts || rejectedPosts.length === 0) ? (
                <p style={{ color: '#666', fontSize: '0.85rem' }}>
                  {lang === 'zh' ? '目前没有被拒绝的帖子。' : 'You have no rejected posts at the moment.'}
                </p>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {rejectedPosts.map((p) => (
                    <div key={p.id} className="card" style={{ border: '1px solid #fecaca', background: '#fef2f2' }}>
                      <div style={{ fontWeight: 'bold', marginBottom: '0.25rem' }}>{p.title || '(no title)'}</div>
                      <div style={{ fontSize: '0.8rem', color: '#991b1b', marginBottom: '0.25rem' }}>
                        {lang === 'zh' ? '状态：已拒绝' : 'Status: REJECTED'}
                      </div>
                      {p.reviewNote && (
                        <div style={{ fontSize: '0.8rem', color: '#7f1d1d' }}>
                          {lang === 'zh' ? '审核理由：' : 'Review note: '}{p.reviewNote}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        );
      default:
        return <PostList />;
    }
  };

  return (
    <div className="browser-window">
      {/* App Container */}
      <div className="app-container">
        {!isLoggedIn ? (
          <LoginPage onLogin={handleLogin} />
        ) : (
          <>
            <Sidebar 
              currentPage={currentPage} 
              onNavigate={handleNavigate}
              isAdmin={isAdmin}
              user={user}
            />
            <main className="main-content">
              {renderMainContent()}
            </main>
          </>
        )}
      </div>
    </div>
  );
};

export default App;

// frontend/src/App.vue
<template>
  <el-config-provider :locale="elementLocale">
    <div class="browser-window">
      <div class="app-container">
      <LoginPage v-if="!isLoggedIn" @login="handleLogin" />
      <template v-else>
        <Sidebar 
          :current-page="currentPage" 
          @navigate="handleNavigate"
          :is-admin="isAdmin"
          :user="user"
        />
        <main class="main-content">
          <!-- Daily Briefing Page -->
          <template v-if="currentPage === 'briefing'">
            <DailyBriefing 
              v-if="!selectedNewsId"
              :key="`briefing-${lang.value}`"
              @view-detail="handleViewNewsDetail" />
            <DailyBriefingDetail
              v-else
              :news-id="selectedNewsId"
              :key="`briefing-detail-${selectedNewsId}-${lang.value}`"
              @back="handleBackToBriefingList" />
          </template>

          <!-- Community Page -->
          <template v-else-if="currentPage === 'community'">
            <div class="section-title" style="display: flex; justify-content: space-between; align-items: center">
              <span>{{ lang === 'zh' ? '社区动态' : 'Community Feed' }}</span>
              <div style="display: flex; gap: 0.5rem">
                <span
                  :class="['pill', { active: selectedTag === 'all' }]"
                  @click="selectedTag = 'all'"
                  style="cursor: pointer"
                >
                  {{ lang === 'zh' ? '全部' : 'All' }}
                </span>
                <span
                  :class="['pill', { active: selectedTag === 'rent' }]"
                  @click="selectedTag = 'rent'"
                  style="cursor: pointer"
                >
                  🏠 #{{ lang === 'zh' ? '租房' : 'Rent' }}
                </span>
                <span
                  :class="['pill', { active: selectedTag === 'learning' }]"
                  @click="selectedTag = 'learning'"
                  style="cursor: pointer"
                >
                  📚 #{{ lang === 'zh' ? '学习' : 'Learning' }}
                </span>
                <span
                  :class="['pill', { active: selectedTag === 'market' }]"
                  @click="selectedTag = 'market'"
                  style="cursor: pointer"
                >
                  🛒 #{{ lang === 'zh' ? '市场' : 'Market' }}
                </span>
                <span
                  :class="['pill', { active: selectedTag === 'visa' }]"
                  @click="selectedTag = 'visa'"
                  style="cursor: pointer"
                >
                  🛂 #{{ lang === 'zh' ? '签证' : 'Visa' }}
                </span>
                <span
                  :class="['pill', { active: selectedTag === 'food' }]"
                  @click="selectedTag = 'food'"
                  style="cursor: pointer"
                >
                  🍜 #{{ lang === 'zh' ? '美食' : 'Food' }}
                </span>
              </div>
            </div>
            <PostList
              :key="`posts-${lang}`"
              @post-click="(postId) => handleNavigate('postDetail', postId)"
              :selected-tag="selectedTag"
            />
          </template>

          <!-- Home View (Legacy - redirects to briefing) -->
          <template v-else-if="currentPage === 'home'">
            <DailyBriefing :key="`briefing-${lang}`" />
          </template>

          <!-- New Post -->
          <NewPostForm v-else-if="currentPage === 'post'" :key="`newpost-${lang}`" :current-user-id="user?.id" />

          <!-- Search -->
          <SearchPanel v-else-if="currentPage === 'search'" :key="`search-${lang}`" />

          <!-- AI Assistant -->
          <NlpAssistant v-else-if="currentPage === 'assistant'" :key="`assistant-${lang}`" />

          <!-- Admin Panel -->
          <template v-else-if="currentPage === 'admin'">
            <AdminPanel v-if="isAdmin" :key="`admin-${lang}`" :token="token" />
            <div v-else class="card">{{ lang === 'zh' ? '无权访问' : 'Access Denied' }}</div>
          </template>

          <!-- Post Detail -->
          <template v-else-if="currentPage === 'postDetail'">
            <PostDetail
              v-if="selectedPostId"
              :key="`detail-${lang}-${selectedPostId}`"
              :post-id="selectedPostId"
              :token="token"
              :current-user-id="user?.id"
              @back="handleNavigate('home')"
            />
            <div v-else class="card">{{ lang === 'zh' ? '帖子未找到' : 'Post not found' }}</div>
          </template>

          <!-- Messages Page -->
          <template v-else-if="currentPage === 'messages'">
            <div style="display: flex; height: calc(100vh - 2rem); gap: 1rem;">
              <!-- Conversation List -->
              <div style="flex: 0 0 350px; border: 2px solid #ddd; border-radius: 8px; overflow: hidden;">
                <ConversationList
                  :token="token"
                  :selected-conversation-id="selectedConversationId"
                  @select-conversation="handleSelectConversation"
                  @back="handleBackToCommunity"
                />
              </div>
              <!-- Chat Window -->
              <div style="flex: 1; border: 2px solid #ddd; border-radius: 8px; overflow: hidden;">
                <ChatWindow
                  v-if="selectedConversationId && selectedConversation"
                  :conversation-id="selectedConversationId"
                  :token="token"
                  :current-user-id="user?.id"
                  :other-user="selectedConversation.otherUser"
                  @message-sent="handleMessageSent"
                />
                <div v-else style="display: flex; align-items: center; justify-content: center; height: 100%; color: #666;">
                  <p>{{ lang === 'zh' ? '请选择一个会话开始聊天' : 'Select a conversation to start chatting' }}</p>
                </div>
              </div>
            </div>
          </template>

          <!-- Profile -->
          <template v-else-if="currentPage === 'profile'">
            <MyProfile 
              v-if="!showMyPostsList"
              :user-id="user?.id"
              :token="token"
              @view-my-posts="showMyPostsList = true"
              @view-post-detail="(postId) => handleNavigate('postDetail', postId)"
            />
            <MyPosts
              v-else
              :token="token"
              @back="showMyPostsList = false"
              @view-post-detail="(postId) => handleNavigate('postDetail', postId)"
            />
          </template>

          <!-- Default -->
          <PostList v-else />
        </main>
      </template>
    </div>
  </div>
  </el-config-provider>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue';
import LoginPage from './components/LoginPage.vue';
import Sidebar from './components/Sidebar.vue';
import PostList from './components/PostList.vue';
import PostDetail from './components/PostDetail.vue';
import SearchPanel from './components/SearchPanel.vue';
import DailyBriefing from './components/vue/DailyBriefing.vue';
import DailyBriefingDetail from './components/vue/DailyBriefingDetail.vue';
import UserProfile from './components/UserProfile.vue';
import MyProfile from './components/MyProfile.vue';
import MyPosts from './components/MyPosts.vue';
import NlpAssistant from './components/NlpAssistant.vue';
import NewPostForm from './components/NewPostForm.vue';
import AdminPanel from './components/AdminPanel.vue';
import ConversationList from './components/ConversationList.vue';
import ChatWindow from './components/ChatWindow.vue';
import { fetchMyRejectedPosts } from './api';
import { setLanguagePreference, getLanguagePreference } from './utils/language';
import { setLanguage, getCurrentLanguage } from './i18n';
// Element Plus locale for dynamic language switching
import zhCn from 'element-plus/dist/locale/zh-cn.mjs';
import en from 'element-plus/dist/locale/en.mjs';
import { ElConfigProvider } from 'element-plus';

// Get initial auth state from localStorage
const getInitialAuthState = () => {
  try {
    const savedToken = localStorage.getItem('token');
    const savedUser = localStorage.getItem('user');
    if (savedToken && savedUser) {
      return {
        isLoggedIn: true,
        token: savedToken,
        user: JSON.parse(savedUser)
      };
    }
  } catch (e) {
    console.error('Failed to restore auth state:', e);
  }
  return { isLoggedIn: false, token: null, user: null };
};

const initialAuth = getInitialAuthState();
const isLoggedIn = ref(initialAuth.isLoggedIn);
const currentPage = ref('briefing'); // Default to briefing page
const selectedPostId = ref(null);
const selectedNewsId = ref(null); // For news detail page
const selectedUserId = ref(null); // For user profile page
const selectedConversationId = ref(null); // For messages page
const selectedConversation = ref(null); // For messages page - stores conversation data
const user = ref(initialAuth.user);
const token = ref(initialAuth.token);
const lang = ref(getCurrentLanguage());
const selectedTag = ref('all');
const rejectedPosts = ref([]);
const showMyPostsList = ref(false);

const isAdmin = computed(() => user.value?.role === 'ADMIN');

// Element Plus locale - 响应语言变化
const elementLocale = computed(() => {
  return lang.value === 'zh' ? zhCn : en;
});

// Listen for language changes and auth errors
onMounted(() => {
  const handleLanguageChange = (e) => {
    if (e && e.detail && e.detail.lang) {
      console.log('App: Language changed to:', e.detail.lang);
      lang.value = e.detail.lang;
      // Element Plus locale 会通过 computed 自动更新
    }
  };
  
  // Listen for unauthorized errors from API interceptor
  const handleUnauthorized = (e) => {
    console.warn('App: Received auth:unauthorized event, logging out user');
    if (isLoggedIn.value) {
      handleLogout();
    }
  };
  
  window.addEventListener('languageChanged', handleLanguageChange);
  window.addEventListener('auth:unauthorized', handleUnauthorized);
  
  // Session management
  sessionStorage.setItem('sessionActive', 'true');
  const wasSessionActive = sessionStorage.getItem('sessionActive');
  if (!wasSessionActive && initialAuth.isLoggedIn) {
    console.log('App: New session detected, clearing auth state');
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    isLoggedIn.value = false;
    user.value = null;
    token.value = null;
  }
  
  // Restore language preference from user
  if (isLoggedIn.value && user.value?.preferredLanguage) {
    const userLang = user.value.preferredLanguage;
    if (userLang === 'zh' || userLang === 'en') {
      setLanguagePreference(userLang);
      setLanguage(userLang);
    }
  }
  
  // Load rejected posts
  if (token.value) {
    loadRejectedPosts();
  }
  
  return () => {
    window.removeEventListener('languageChanged', handleLanguageChange);
    window.removeEventListener('auth:unauthorized', handleUnauthorized);
    window.removeEventListener('viewUserProfile', handleViewUserProfile);
  };
});

// Watch for token changes to load rejected posts
watch(token, (newToken) => {
  if (newToken) {
    loadRejectedPosts();
  }
});

const loadRejectedPosts = async () => {
  try {
    if (!token.value) return;
    const data = await fetchMyRejectedPosts();
    rejectedPosts.value = Array.isArray(data) ? data : [];
  } catch (e) {
    console.error('Failed to load rejected posts', e);
    
    // 如果是认证错误，清除 token 并登出用户
    if (e.response?.status === 401 || e.isAuthError) {
      console.warn('🔒 Authentication failed (401), logging out user');
      handleLogout();
      // 不需要显示错误消息，因为用户会被重定向到登录页面
    }
  }
};

const handleLogin = (userData, authToken) => {
  console.log('App: handleLogin called, userData:', userData);
  isLoggedIn.value = true;
  user.value = userData;
  token.value = authToken;
  
  if (authToken) {
    localStorage.setItem('token', authToken);
    console.log('App: Token saved to localStorage');
  }
  if (userData) {
    localStorage.setItem('user', JSON.stringify(userData));
  }
  currentPage.value = 'briefing'; // Default to briefing page
  
  if (userData && userData.preferredLanguage) {
    const userLang = userData.preferredLanguage;
    console.log('App: User preferredLanguage:', userLang);
    if (userLang === 'zh' || userLang === 'en') {
      console.log('App: Setting language to:', userLang);
      setLanguagePreference(userLang);
      setLanguage(userLang);
    }
  } else {
    const savedLang = localStorage.getItem('userLanguage');
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      console.log('App: Using saved language from localStorage:', savedLang);
      setLanguage(savedLang);
    }
  }
};

const handleLogout = () => {
  console.log('App: Logging out user');
  isLoggedIn.value = false;
  user.value = null;
  token.value = null;
  rejectedPosts.value = [];
  showMyPostsList.value = false;
  currentPage.value = 'briefing'; // Reset to default page
  selectedPostId.value = null;
  selectedNewsId.value = null;
  selectedUserId.value = null;
  selectedConversationId.value = null;
  selectedConversation.value = null;
  localStorage.removeItem('token');
  localStorage.removeItem('user');
  sessionStorage.removeItem('sessionActive');
};

const handleNavigate = (page, postId = null) => {
  if (page === 'logout') {
    handleLogout();
    return;
  }
  if (page === 'postDetail' && postId) {
    selectedPostId.value = postId;
    currentPage.value = 'postDetail';
    selectedNewsId.value = null;
    selectedUserId.value = null;
    selectedConversationId.value = null;
    selectedConversation.value = null;
    showMyPostsList.value = false;
  } else if (page === 'messages') {
    currentPage.value = 'messages';
    selectedPostId.value = null;
    selectedNewsId.value = null;
    selectedUserId.value = null;
    showMyPostsList.value = false;
    // Keep conversation selection when navigating to messages
  } else if (page === 'profile') {
    currentPage.value = 'profile';
    showMyPostsList.value = false;
    selectedPostId.value = null;
    selectedNewsId.value = null;
    selectedUserId.value = null;
    selectedConversationId.value = null;
    selectedConversation.value = null;
  } else {
    currentPage.value = page;
    selectedPostId.value = null;
    selectedNewsId.value = null; // Reset news detail when navigating away
    selectedUserId.value = null; // Reset user profile when navigating away
    selectedConversationId.value = null; // Reset conversation when navigating away
    selectedConversation.value = null;
    showMyPostsList.value = false;
  }
};

const handleViewNewsDetail = (newsId) => {
  selectedNewsId.value = newsId;
};

const handleBackToBriefingList = () => {
  selectedNewsId.value = null;
};

const handleBackFromProfile = () => {
  selectedUserId.value = null;
  currentPage.value = 'community'; // Go back to community page
};

const handlePostClickFromProfile = (postId) => {
  selectedPostId.value = postId;
  currentPage.value = 'postDetail';
};

const handleSendMessageFromProfile = (userId) => {
  // Navigate to messages page and create/select conversation
  handleNavigate('messages');
  // The conversation will be created when user selects it from the list
  // or we can auto-create it here if needed
};

const handleSelectConversation = (conversation) => {
  if (conversation) {
    selectedConversationId.value = conversation.id;
    selectedConversation.value = conversation;
  } else {
    selectedConversationId.value = null;
    selectedConversation.value = null;
  }
};

const handleMessageSent = () => {
  // Refresh conversation list when a message is sent
  // This will be handled by the ConversationList component if we expose a refresh method
  console.log('Message sent, conversation list should refresh');
};

const handleBackToCommunity = () => {
  currentPage.value = 'community';
  selectedConversationId.value = null;
  selectedConversation.value = null;
};
</script>

<style scoped>
/* Styles are in styles.css */
</style>
